<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOuBwaHO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOuBwaHO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOuBwaHO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOuBwaHO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOuBwaHO\App_KernelDevDebugContainer([
    'container.build_hash' => 'OuBwaHO',
    'container.build_id' => '9858b8e4',
    'container.build_time' => 1644937906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOuBwaHO');
