<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIMwMSC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIMwMSC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRIMwMSC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRIMwMSC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRIMwMSC\App_KernelDevDebugContainer([
    'container.build_hash' => 'RIMwMSC',
    'container.build_id' => '93ddfdc8',
    'container.build_time' => 1642287422,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIMwMSC');
